### ISSUE TITLE
Get file attributes?

### ISSUE THREAD

**Issue by adonespitogo** [Aymkdn/FileToDataURI#7]
Hi, is there a way to get file attributes like file size, file name and file type?

**Comment by Aymkdn** [comment]
With the actual code, no it doesn't provide this information.

The purpose of `FileToDataURI` is only to have a cross-browser solution to read a local file and provide the base64 encoded content.

If you target the modern browsers you can play with `FileReader API` and `File API` to get file size, file name and file type, otherwise I'm not sure it's possible with old browsers... you'll have to ask to Google!
